require "json"
require "search_result"

# Second-layout regression (DESIGN.md Section 5). The Picasso page is a more recent
# capture whose obfuscated class names differ from van-gogh's, proving the parser
# must not depend on them.
#
# Unlike van-gogh, there is no SerpApi-provided example. files/pablo-picasso-expected-array.json
# is a *snapshot* generated by this parser (and spot-verified against the HTML), so
# the golden-match below guards against regressions/drift, while the explicit counts
# below are the independent, inspection-derived check.
RSpec.describe "Pablo Picasso paintings page (second layout)" do
  let(:files_dir) { File.expand_path("../../files", __dir__) }
  let(:result) { SearchResult.from_file(File.join(files_dir, "pablo-picasso-paintings.html")) }
  let(:expected) { JSON.parse(File.read(File.join(files_dir, "pablo-picasso-expected-array.json"))) }
  let(:artworks) { result.to_h["artworks"] }

  it "matches the picasso snapshot exactly" do
    expect(result.to_h).to eq(expected)
  end

  it "extracts all 45 carousel paintings despite rotated class names" do
    expect(artworks.size).to eq(45)
  end

  it "gives every artwork a non-empty name and an absolute link" do
    expect(artworks.map { |a| a["name"] }).to all(be_a(String).and(be_truthy))
    expect(artworks.map { |a| a["name"] }).to all(satisfy { |n| !n.empty? })
    expect(artworks.map { |a| a["link"] }).to all(start_with("https://www.google.com/search?"))
  end

  it "resolves images: 8 inline base64 + 37 thumbnail URLs, none missing" do
    images = artworks.map { |a| a["image"] }
    expect(images.count { |i| i.to_s.start_with?("data:image/jpeg;base64,") }).to eq(8)
    expect(images.count { |i| i.to_s.start_with?("https://encrypted-tbn") }).to eq(37)
    expect(images).to all(be_truthy)
  end

  it "extracts dates as extensions where present (39 of 45)" do
    with_dates = artworks.count { |a| a.key?("extensions") }
    expect(with_dates).to eq(39)
  end

  it "spot-checks the first artwork" do
    first = artworks.first
    expect(first["name"]).to eq("Guernica")
    expect(first["extensions"]).to eq(["1937"])
    expect(first["image"]).to start_with("data:image/jpeg;base64,")
  end
end
